### ISSUE TITLE
duplicate results!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [dmdhrumilmistry/MusicAPy#2]
hello there!!!congratulations for your amazing project!but please could you remove alla duplicate results?it would be great!!!

**Comment by dmdhrumilmistry** [comment]
> hello there!!!congratulations for your amazing project!but please could you remove alla duplicate results?it would be great!!!

Thanks for using the project.
Can you provide more information regarding the issue? if it's possible could you provide an example, that could be helpful.

**Comment by KENPOKASMMA1982** [comment]
hello my friend!!!look many songs appeared 2 and three times!!!you can check the web of  jiosaavn!many duplicate songs and albums...but more songs!it would be great if you can remove with some way!!!

**Comment by dmdhrumilmistry** [comment]
okay, package will be updated to remove duplicates entries soon.

**Comment by dmdhrumilmistry** [comment]
@KENPOKASMMA1982 there aren't any duplicate results, they are the links of the same song in different audio qualities.

**Comment by KENPOKASMMA1982** [comment]
my friend do you have facebook?if,yes this is mine!accep please!!!  https://www.facebook.com/panos.papadopulos/

**Comment by dmdhrumilmistry** [comment]
I'm closing this issue, this project is wrapper for the various apis, so the results are fetched from the apis.
