### ISSUE TITLE
help please!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [dmdhrumilmistry/MusicAPy#3]
my good friend Before uninstall python tomorrow morning I could download with python from spotyfy spotdl!but now I cant my friend!please can you tell me the correct commands on cmd to run pip3 and python???please dude help me!!!

C:\Users\User>pip3 install
Defaulting to user installation because normal site-packages is not writeable
ERROR: You must give at least one requirement to install (see "pip help install")
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.

**Comment by dmdhrumilmistry** [comment]
> my good friend Before uninstall python tomorrow morning I could download with python from spotyfy spotdl!but now I cant my friend!please can you tell me the correct commands on cmd to run pip3 and python???please dude help me!!!
> 
> C:\Users\User>pip3 install Defaulting to user installation because normal site-packages is not writeable ERROR: You must give at least one requirement to install (see "pip help install") WARNING: You are using pip version 22.0.4; however, version 22.1 is available. You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.

This repo provides only support for this MusicAPy package, you should create an issue on their repo.
